#!/bin/bash

FUSIONPBX_DB_HOST=
FUSIONPBX_DB_PORT=
FUSIONPBX_DB_NAME=
FUSIONPBX_DB_USER=
FUSIONPBX_DB_PASS=

FREESWITCH_DB_HOST=
FREESWITCH_DB_PORT=
FREESWITCH_DB_NAME=
FREESWITCH_DB_USER=
FREESWITCH_DB_PASS=
